spring:
  # DB 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onstyle?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ejc
    password: eunjicho0000
  # JPA 설정
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false

server:
  port: 8088
  servlet:
    context-path: /rest